// DO NOT EDIT THIS FILE! see README.TXT - Javascript Compressor 1.1.0
var token;
var name_groupe="";
var index_billet=-1;
var name;
function refresh(){
setTimeout("refresh();",5000);
}
function select(action){
if(action=="pseudo"){
var p=$('#pseudo').val();
name=p;
$.ajax({
url:"https://192.168.75.13/api/v2/users/login",
type:"POST",
contentType:"application/json",
headers:{
"Accept":"application/json",
'Authorization':token,
},
data:"{ \"pseudo\" : \""+p+"\" }",
error:function(resultat,statut,error){
}
}).done(function(data,response,head){
token=head.getResponseHeader("Authorization");
var_pseudo={
pseudo:p
};
var output=Mustache.render("Pseudo {{pseudo}}",_pseudo);
$('#mu').html(output);
alert("pseudo "+p+" ok");
});
}
if(action=="groupe"){
$.ajax({
url:"https://192.168.75.13/api/v2/groupes/"+name_groupe+"/billets",
type:"GET",
contentType:"application/json",
headers:{
"Accept":"application/json",
'Authorization':token,
},
error:function(resultat,statut,error){
}
}).done(function(data,response,head){
var Groupe={
Groupe:data
};
var output_billets=Mustache.render("{{#Groupe}}"+"<cite contenteditable=\"true\"> {{.}} <cite> <br/> {{/Groupe}}",Groupe);
$('#bltList').html(output_billets);
});
}
var commentaire={
auteur:"vercingetorix",
texte:"j'ai gagne gergovie"
};
if(action=="groupes"){
console.log(name);
name_groupe=null;
name_groupe=$('#groupe').val();
var desc=$('#desc').val();
$.ajax({
url:"https://192.168.75.13/api/v2/groupes",
type:"GET",
headers:{
"Accept":"application/json",
},
sucess:function(data){
},
error:function(resultat,statut,error){
console.log("token : "+token)
console.log(statut);
}
}).done(function(data,response,head){
var Groupes={
groupes:data
};
var output_groupes=Mustache.render("Groupes : "+
"<li class=\"list-group-item\">"+"{{#groupes}} "+"<br/> {{.}} "+"{{/groupes}}"+"</li>",Groupes);
$('#groupesList').html(output_groupes);
});
if(name_groupe!=""){
$.ajax({
url:"https://192.168.75.13/api/v2/groupes",
type:"POST",
contentType:"application/json",
headers:{
"Accept":"application/json",
'Authorization':token,
},
data:"{ \"nom\" : \""+name_groupe+"\" "+", \"description\" : \""+desc+"\" }",
error:function(resultat,statut,error){
}
}).done(function(data,response,head){
alert("Groupe "+name_groupe+" ok");
});
}
}
var Billets={
billets:["b1","b2"]
};
var Commentaires={
commentaires:["yolo1","yolo2"]
};
if(action=="users"){
$.ajax({
url:"https://192.168.75.13/api/v2/users",
type:"GET",
headers:{
"Accept":"application/json",
"Authorization":token
},
error:function(resultat,statut,error){
console.log("token : "+token)
console.log(statut);
}
}).done(function(data,response,head){
var Users={
users:data
};
var output=Mustache.render("{{#users}} "+"<br/> {{.}} "+"{{/users}}",Users);
$('#usersList').html(output);
});
}
if(action=="billet"){
var billet={
titre:"mon billet",
contenue:" voici mon contenue",
auteur:"toto",
commentaire:["c1","c2","c3"," il fait beau on est en retard"]
};
$.ajax({
url:"https://192.168.75.13/api/v2/groupes/"+name_groupe+"/billets",
type:"GET",
contentType:"application/json",
headers:{
"Accept":"application/json",
'Authorization':token,
},
error:function(resultat,statut,error){
console.log(statut);
}
}).done(function(data,response,head){
});
}
if(action=='billets'){
var titre="";
titre=$('#titre').val();
var desc=$('#contenu').val();
console.log("titre : "+titre+" contenu : "+desc);
if(titre==""){
fetch("https://192.168.75.13/api/v2/groupes/"+name_groupe+"/billets/"+index_billet,{
method:"GET",
mode:"cors",
headers:{
"Accept":"application/json",
'Authorization':token,
}
})
.then(response=>{
if(response.ok){
return response.json();
}
throw new Error('ErreurHTTP : '+response.status);})
.then(function(data){
var Groupe={
billets:data
};
var output_billets=Mustache.render("<li class=\"list-group-item\">"+"{{#billets}} "+"<cite contenteditable=\"true\">"+"<br/> {{titre}} "+" "+" {{contenu}} "+"<cite>"+"{{/billets}}"+"</li>",Groupe);
$('#bltList').html(output_billets);
});
}
else{
$.ajax({
url:"https://192.168.75.13/api/v2/groupes/"+name_groupe+"/billets",
type:"POST",
contentType:"application/json",
headers:{
"Accept":"application/json",
'Authorization':token,
},
data:"{ \"titre\" : \""+titre+"\" "+", \"contenu\" : \""+desc+"\" }",
error:function(resultat,statut,error){
}
}).done(function(){
index_billet=index_billet+1;
alert("billet ok");
});
}
}
if(action=="commentaire"){
var commentaire="";
commentaire=$('#commentaire').val();
if(commentaire!=""){
$.ajax({
url:"https://192.168.75.13/api/v2/groupes/"+name_groupe+"/billets/"+index_billet+"/commentaires",
type:"POST",
contentType:"application/json",
headers:{
"Accept":"application/json",
'Authorization':token,
},
data:"{ \"auteur\" : \""+name+"\" "+", \"texte\" : \""+commentaire+"\" }",
sucess:function(data){
console.log(data);
},
error:function(resultat,statut,error){
console.log(statut);
}
}).done(function(data){
});
}else{
$.ajax({
url:"https://192.168.75.13/api/v2/groupes/"+name_groupe+"/billets/"+index_billet+"/commentaires",
type:"GET",
contentType:"application/json",
headers:{
"Accept":"application/json",
'Authorization':token,
},
sucess:function(data){
},
error:function(resultat,statut,error){
console.log(statut);
}
}).done(function(data){
var commentaires={
commentaires:data
};
var output_commentaires=Mustache.render("{{#commentaires}} "+"<br/> {{.}} "+"{{/commentaires}}",commentaires);
$('#commentList').html(output_commentaires);
});
}
}
if(action=='deco'){
var checkbox=$('#chkbox').is(":checked");
var pseudo=$('#name').val();
$.ajax({
url:"https://192.168.75.13/api/v2/users/logout",
type:"POST",
contentType:"application/json",
headers:{
"Accept":"application/json",
'Authorization':token,
},
data:"{ \"pseudo\" : \"" + pseudo + "\" }",
error:function(resultat,statut,error){
}
}).done(function(){
});
if(checkbox){
}
name="";
token="";
}
}
function loadXMLAsynchroneously(method,request,parameters,id)
{
var xhr=initRequete();
var XMLDoc=null;
xhr.onreadystatechange=function(){getXMLDocument(xhr,XMLDoc,id);};
xhr.open(method,request,true);
if(parameters&&(method=="post"||method=="POST"))
xhr.setRequestHeader('Content-Type','application/x-www-form-urlencoded');
xhr.send(parameters);
}
function sendRequestAsynchroneously(method,request,parameters)
{
var xhr=initRequete();
xhr.open(method,request,true);
if(parameters&&(method=="post"||method=="POST"))
xhr.setRequestHeader('Content-Type','application/x-www-form-urlencoded');
xhr.send(parameters);
}
function getXMLDocument(xhr,XMLDoc,id)
{
if(xhr.readyState==4){
if(xhr.status==200){
if(xhr.responseXML!=null){
XMLDoc=xhr.responseXML;
}else if(xhr.responseText!=null){
XMLDoc=parseFromString(xhr.responseText);
}
traiteXML(XMLDoc,id);
}else if(xhr.status>=400&&xhr.status!=1223){
alert("Un probl�me est survenu avec la requ�te : ");
}
}
}
function initRequete()
{
var xhr=null;
if(window.XMLHttpRequest){
xhr=new XMLHttpRequest();
}
else if(window.ActiveXObject)
{
xhr=new ActiveXObject("Microsoft.XMLHTTP");
}
return xhr;
}
function parseFromString(docTXT){
if(window.ActiveXObject)
{
var XMLDoc=new ActiveXObject("Microsoft.XMLDOM");
XMLDoc.async="false";
XMLDoc.loadXML(docTXT);
}
else
{
var parser=new DOMParser();
var XMLDoc=parser.parseFromString(docTXT,"text/xml");
}
return XMLDoc;
}
function getXMLTextContent(source)
{
if(source.textContent!=null){
return source.textContent;
}else{
return source.text;
}
}
function traiteXML(_XMLDoc,_id)
{
var h=_XMLDoc.getElementsByTagName("h")[0].childNodes[0].nodeValue;
var m=_XMLDoc.getElementsByTagName("m")[0].childNodes[0].nodeValue;
var s=_XMLDoc.getElementsByTagName("s")[0].childNodes[0].nodeValue;
console.log(h);
document.getElementById(_id).innerHTML="<p>"+"heure ="+h+"minute = "+m+"seconde = "+s+"</p>";
var xsltprocessor=new XSLTProcessor();
transform(_XMLDoc,xsltprocessor,_id);
}
function transform(XMLDoc,XSLDoc,id){
if(XMLDoc==null||XSLDoc==null){return;}
try{
if(window.ActiveXObject){
var target=document.getElementById(id);
target.innerHTML=traiteXML.transformNode(xsl);
}else if(window.XSLTProcessor){
var fragment;
var xsltProcessor=new XSLTProcessor();
xsltProcessor.importStylesheet(xsl);
fragment=xsltProcessor.transformToFragment(xml,document);
var target=document.getElementById(id);
target.appendChild(fragment);
}
}catch(e){
return e;
}
}
